var angular = require('angular');
var firebase = require('firebase/app');
require('firebase/auth');
require('angular-aria');
require('angular-animate');
require('angular-material/angular-material.css');
require('angular-material-data-table/dist/md-data-table.min.css');
require('angular-material-sidemenu/dest/angular-material-sidemenu.css');
require('lodash');
require('./app')(angular, firebase);